### ISSUE TITLE
android.os.NetworkOnMainThreadException

### ISSUE THREAD

**Issue by mehturt** [Mobicents/restcomm-android-sdk#12]
I'm getting this exception when specifying hostname as the proxy IP.  Is this expected?

**Comment by atsakiridis** [comment]
Correct, by default a domain lookup is not allowed to be conducted on the main thread because it would block it and have undesired side-effects in the UI experience :(. Solution would be to perform that action on a separate thread.

I'll try to check this as soon as possible but in the meantime if you 'd like to get your hands dirty and contribute a fix, that 'd be great :)

**Comment by mehturt** [comment]
Yes, I fixed this already locally, however I made many changes to the example to fit my needs.  I've never contributed via github, will see what I can do about it.

**Comment by atsakiridis** [comment]
Great :) If you decide to, please issue a pull request

**Comment by atsakiridis** [comment]
Fixes need be placed in three locations:
- making call using DNS
- sending message using DNS
- registering using DNS
