### ISSUE TITLE
RestComm Messenger : Call to Live Instance Fails

### ISSUE THREAD

**Issue by deruelle** [Mobicents/restcomm-android-sdk#123]
I was able to make one call but got disconnected after like 1-2 minutes.
All other subsequent calls are stuck on received offer from remote.

**Comment by atsakiridis** [comment]
@deruelle: tried calling bridge (application 1311) and call is fine, I left the call active for around 3-5 minutes and wasn't disconnected.

But then I tried calling alice @ olympus and:
- if I answer from olympus with audio the call is indeed stuck
- if I answer from olympus with video it's fine

That happens because I haven't added an option to call only audio yet, so all calls are video. The problem is that when olympus answers the call with audio, it doesn't add a m=video line at all, although I think it should, so that m lines between offer and answer are 1-to-1

@hrosa: do we have an issue about that in Olympus?

**Comment by atsakiridis** [comment]
I'll keep this issue to address the Messenger hang/crash and we'll keep webrtcomm #10 for the SDP issue which is the root cause
