### ISSUE TITLE
JAIN-SIP project does not compile

### ISSUE THREAD

**Issue by vumaasha** [Mobicents/restcomm-android-sdk#190]
unable to run jain sip demo as the code is not updated to reflect the changes in sipua

**Comment by atsakiridis** [comment]
@vumaasha, I'd suggest migrating to the new, higher level API: restcomm.android.client.sdk (https://github.com/Mobicents/restcomm-android-sdk/tree/master/restcomm.android.client.sdk), instead of the old (i.e. sipua) used by the JAIN SIP sample application because sipua is not supported anymore. Also you can find a similar sample application utilizing the new API at:

https://github.com/Mobicents/restcomm-android-sdk/tree/master/Examples/restcomm-messenger

Also, here's the quick start guide:

http://docs.telestax.com/restcomm-client-android-sdk-quick-start/
