### ISSUE TITLE
cannot hangup the call by calling method Hangup()

### ISSUE THREAD

**Issue by pankajsewalia01** [Mobicents/restcomm-android-sdk#45]
i am developing a softphone using restcomm-android-sdk, everything is fine except when i disconnect the call using Hangup() then both callee and caller phone doesnot disconnected

**Comment by atsakiridis** [comment]
Which commit are you using? Because there have been some fixes in the hangup functionality the last few days.

**Comment by pankajsewalia01** [comment]
i tested with latest commit aa1e137b1f, result is same

**Comment by atsakiridis** [comment]
I'd suggest migrating to the new, higher level API: restcomm.android.client.sdk (https://github.com/Mobicents/restcomm-android-sdk/tree/master/restcomm.android.client.sdk), instead of the old (i.e. sipua) used by the JAIN SIP sample application because sipua is not supported anymore. Also you can find a similar sample application utilizing the new API at:

https://github.com/Mobicents/restcomm-android-sdk/tree/master/Examples/restcomm-messenger

Also, here's the reference documentation to get an idea of the APIs involved:

http://mobicents.github.io/restcomm-android-sdk/doc/
